### PR TITLE
Update rest-client dependency

### PR DESCRIPTION
**Pull request by etruong42**

### CODE REVIEW

**Comment by mkostick** [comment]
Is this actually required?  It doesn't look like we're using this fork.

**Comment by etruong42** [comment]
We'd be using the fork here: https://github.com/Yesware/Backend/pull/6394

**Comment by etruong42** [comment]
tagging reviewers @dmills-yesware @mkostick

**Comment by dmills-yesware** [comment]
LGTM

**Comment by etruong42** [comment]
Closing as Backend is reading from this branch (no need to merge): https://github.com/Yesware/Backend/pull/6394/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R135

**Pull request closed without merging**
